/* Generated By:JavaCC: Do not edit this line. SpiffTreeParserTreeConstants.java Version 5.0 */
package com.revbingo.spiff.parser;

public interface SpiffTreeParserTreeConstants
{
  public int JJTADF = 0;
  public int JJTDATATYPEDEFS = 1;
  public int JJTLIST = 2;
  public int JJTENTRY = 3;
  public int JJTBITS = 4;
  public int JJTBYTES = 5;
  public int JJTNUMBERTYPE = 6;
  public int JJTINSTRUCTION = 7;
  public int JJTSTRING = 8;
  public int JJTINCLUDEINSTRUCTION = 9;
  public int JJTDEFINEINSTRUCTION = 10;
  public int JJTSETENCODINGINSTRUCTION = 11;
  public int JJTSETINSTRUCTION = 12;
  public int JJTPRINTINSTRUCTION = 13;
  public int JJTIFINSTRUCTION = 14;
  public int JJTSETORDERINSTRUCTION = 15;
  public int JJTREPEATINSTRUCTION = 16;
  public int JJTGROUPINSTRUCTION = 17;
  public int JJTJUMPINSTRUCTION = 18;
  public int JJTSKIPINSTRUCTION = 19;
  public int JJTMARKINSTRUCTION = 20;
  public int JJTFIXEDSTRING = 21;
  public int JJTLITERALSTRING = 22;
  public int JJTTERMINATEDSTRING = 23;
  public int JJTFIXEDNUMBER = 24;
  public int JJTEXPRESSION = 25;
  public int JJTCOMPARATOR = 26;
  public int JJTADDITIVEEXPRESSION = 27;
  public int JJTMULTIPLICATIVEEXPRESSION = 28;
  public int JJTUNARYEXPRESSION = 29;
  public int JJTFUNCTIONCALL = 30;
  public int JJTFORMALPARAMETERS = 31;
  public int JJTVOID = 32;


  public String[] jjtNodeName = {
    "adf",
    "datatypeDefs",
    "list",
    "entry",
    "bits",
    "bytes",
    "numberType",
    "instruction",
    "string",
    "includeInstruction",
    "defineInstruction",
    "setEncodingInstruction",
    "setInstruction",
    "printInstruction",
    "ifInstruction",
    "setOrderInstruction",
    "repeatInstruction",
    "groupInstruction",
    "jumpInstruction",
    "skipInstruction",
    "markInstruction",
    "fixedString",
    "literalString",
    "terminatedString",
    "fixedNumber",
    "expression",
    "comparator",
    "additiveExpression",
    "multiplicativeExpression",
    "unaryExpression",
    "functionCall",
    "FormalParameters",
    "void",
  };
}
/* JavaCC - OriginalChecksum=3fca8f804fcf986cd2e5f224c00bcc2b (do not edit this line) */
