/* Generated By:JavaCC: Do not edit this line. SpiffParserConstants.java */
/******************************************************************************* * This file is part of SPIFF. *  * SPIFF is free software: you can redistribute it and/or modify * it under the terms of the GNU General Public License as published by * the Free Software Foundation, either version 3 of the License, or * (at your option) any later version. *  * SPIFF is distributed in the hope that it will be useful, * but WITHOUT ANY WARRANTY; without even the implied warranty of * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the * GNU General Public License for more details. *  * You should have received a copy of the GNU General Public License * along with SPIFF.  If not, see <http://www.gnu.org/licenses/>. ******************************************************************************/
package com.revbingo.spiff.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SpiffParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TY_STRING = 3;
  /** RegularExpression Id. */
  int TY_INT = 4;
  /** RegularExpression Id. */
  int TY_LONG = 5;
  /** RegularExpression Id. */
  int TY_BYTE = 6;
  /** RegularExpression Id. */
  int TY_SHORT = 7;
  /** RegularExpression Id. */
  int TY_DOUBLE = 8;
  /** RegularExpression Id. */
  int TY_FLOAT = 9;
  /** RegularExpression Id. */
  int TY_UBYTE = 10;
  /** RegularExpression Id. */
  int TY_USHORT = 11;
  /** RegularExpression Id. */
  int TY_UINT = 12;
  /** RegularExpression Id. */
  int TY_ULONG = 13;
  /** RegularExpression Id. */
  int TY_BITS = 14;
  /** RegularExpression Id. */
  int TY_BYTES = 15;
  /** RegularExpression Id. */
  int EOL = 16;
  /** RegularExpression Id. */
  int BYTEORDER = 17;
  /** RegularExpression Id. */
  int ENCODING = 18;
  /** RegularExpression Id. */
  int END = 19;
  /** RegularExpression Id. */
  int OPEN_PAR = 20;
  /** RegularExpression Id. */
  int CLOSE_PAR = 21;
  /** RegularExpression Id. */
  int OPEN_BRACE = 22;
  /** RegularExpression Id. */
  int CLOSE_BRACE = 23;
  /** RegularExpression Id. */
  int COMMA = 24;
  /** RegularExpression Id. */
  int QUOTE = 25;
  /** RegularExpression Id. */
  int INS_JUMP = 26;
  /** RegularExpression Id. */
  int INS_SETORDER = 27;
  /** RegularExpression Id. */
  int INS_REPEAT = 28;
  /** RegularExpression Id. */
  int INS_GROUP = 29;
  /** RegularExpression Id. */
  int INS_SKIP = 30;
  /** RegularExpression Id. */
  int INS_IF = 31;
  /** RegularExpression Id. */
  int INS_SET = 32;
  /** RegularExpression Id. */
  int INS_PRINT = 33;
  /** RegularExpression Id. */
  int INS_ELSE = 34;
  /** RegularExpression Id. */
  int INS_MARK = 35;
  /** RegularExpression Id. */
  int INS_SETENCODING = 36;
  /** RegularExpression Id. */
  int INS_DEFINE = 37;
  /** RegularExpression Id. */
  int INS_INCLUDE = 38;
  /** RegularExpression Id. */
  int INS_DATATYPE = 39;
  /** RegularExpression Id. */
  int EQUAL = 40;
  /** RegularExpression Id. */
  int GREATER_THAN = 41;
  /** RegularExpression Id. */
  int LESS_THAN = 42;
  /** RegularExpression Id. */
  int NOT_EQUAL = 43;
  /** RegularExpression Id. */
  int GREATER_OR_EQUAL = 44;
  /** RegularExpression Id. */
  int LESS_OR_EQUAL = 45;
  /** RegularExpression Id. */
  int PL_MI_OPERATOR = 46;
  /** RegularExpression Id. */
  int MUL_DIV_OPERATOR = 47;
  /** RegularExpression Id. */
  int IDENTIFIER = 48;
  /** RegularExpression Id. */
  int ID_VALUE = 49;
  /** RegularExpression Id. */
  int CLASS = 50;
  /** RegularExpression Id. */
  int ID_ADDRESS = 51;
  /** RegularExpression Id. */
  int COMMENT = 52;
  /** RegularExpression Id. */
  int FLOAT = 53;
  /** RegularExpression Id. */
  int HEX_INTEGER = 54;
  /** RegularExpression Id. */
  int INTEGER = 55;
  /** RegularExpression Id. */
  int ALPHANUM = 56;
  /** RegularExpression Id. */
  int DIGIT = 57;
  /** RegularExpression Id. */
  int ALPHA = 58;
  /** RegularExpression Id. */
  int UNDERSCORE = 59;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"string\"",
    "\"int\"",
    "\"long\"",
    "\"byte\"",
    "\"short\"",
    "\"double\"",
    "\"float\"",
    "\"ubyte\"",
    "\"ushort\"",
    "\"uint\"",
    "\"ulong\"",
    "\"bits\"",
    "\"bytes\"",
    "<EOL>",
    "<BYTEORDER>",
    "<ENCODING>",
    "<END>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\"\\\'\"",
    "\".jump\"",
    "\".setorder\"",
    "\".repeat\"",
    "\".group\"",
    "\".skip\"",
    "\".if\"",
    "\".set\"",
    "\".print\"",
    "\".else\"",
    "\".mark\"",
    "\".setencoding\"",
    "\".define\"",
    "\".include\"",
    "\".datatype\"",
    "\"==\"",
    "\">\"",
    "\"<\"",
    "\"!=\"",
    "\">=\"",
    "\"<=\"",
    "<PL_MI_OPERATOR>",
    "<MUL_DIV_OPERATOR>",
    "<IDENTIFIER>",
    "<ID_VALUE>",
    "<CLASS>",
    "<ID_ADDRESS>",
    "<COMMENT>",
    "<FLOAT>",
    "<HEX_INTEGER>",
    "<INTEGER>",
    "<ALPHANUM>",
    "<DIGIT>",
    "<ALPHA>",
    "\"_\"",
  };

}
