/* Generated By:JavaCC: Do not edit this line. SpiffParserTreeConstants.java Version 5.0 */
package com.revbingo.spiff.parser;

public interface SpiffParserTreeConstants
{
  public int JJTPARSE = 0;
  public int JJTDATATYPEDEFS = 1;
  public int JJTLIST = 2;
  public int JJTENTRY = 3;
  public int JJTBITS = 4;
  public int JJTBYTES = 5;
  public int JJTINSTRUCTION = 6;
  public int JJTSTRING = 7;
  public int JJTINCLUDEINSTRUCTION = 8;
  public int JJTDEFINEINSTRUCTION = 9;
  public int JJTSETENCODINGINSTRUCTION = 10;
  public int JJTSETINSTRUCTION = 11;
  public int JJTPRINTINSTRUCTION = 12;
  public int JJTIFINSTRUCTION = 13;
  public int JJTSETORDERINSTRUCTION = 14;
  public int JJTREPEATINSTRUCTION = 15;
  public int JJTGROUPINSTRUCTION = 16;
  public int JJTJUMPINSTRUCTION = 17;
  public int JJTSKIPINSTRUCTION = 18;
  public int JJTMARKINSTRUCTION = 19;
  public int JJTFIXEDSTRING = 20;
  public int JJTLITERALSTRING = 21;
  public int JJTTERMINATEDSTRING = 22;
  public int JJTFIXEDNUMBER = 23;
  public int JJTFIXEDUNSIGNED = 24;
  public int JJTEXPRESSION = 25;
  public int JJTCOMPARATOR = 26;
  public int JJTADDITIVEEXPRESSION = 27;
  public int JJTMULTIPLICATIVEEXPRESSION = 28;
  public int JJTUNARYEXPRESSION = 29;
  public int JJTFUNCTIONCALL = 30;
  public int JJTFORMALPARAMETERS = 31;
  public int JJTFORMALPARAMETER = 32;
  public int JJTNUMBERTYPE = 33;
  public int JJTUNSIGNEDNUMBERTYPE = 34;


  public String[] jjtNodeName = {
    "parse",
    "datatypeDefs",
    "list",
    "entry",
    "bits",
    "bytes",
    "instruction",
    "string",
    "includeInstruction",
    "defineInstruction",
    "setEncodingInstruction",
    "setInstruction",
    "printInstruction",
    "ifInstruction",
    "setOrderInstruction",
    "repeatInstruction",
    "groupInstruction",
    "jumpInstruction",
    "skipInstruction",
    "markInstruction",
    "fixedString",
    "literalString",
    "terminatedString",
    "fixedNumber",
    "fixedUnsigned",
    "expression",
    "comparator",
    "additiveExpression",
    "multiplicativeExpression",
    "unaryExpression",
    "functionCall",
    "FormalParameters",
    "FormalParameter",
    "numberType",
    "unsignedNumberType",
  };
}
/* JavaCC - OriginalChecksum=1ae4c9ea5969f1fef13958e032684538 (do not edit this line) */
